spring:
  profiles:
    active: local

---
# job.name? ???? ?? Job? ??. ???? ??? NONE. ?, ?? Job? ???? ??
spring.batch.job.names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alfredbatch
    username: root
    password: root