spring:
  profiles:
    active: local

---
# job.name을 파라미터로 받아서 해당 Job만 실행시킨다. 파라미터가 없을경우 NONE. 즉, 아무 Job도 실행하지 않는다.
spring.batch.job.names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    bard:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/alfredbatch
      username: root
      password: Gnlfhfh12@
    alfred:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/saas-alfredtestdb
      username: root
      password: Gnlfhfh12@

logging:
  level:
    org.springframework.batch: DEBUG